[package]
name = "neuclidio"
version = "0.1.0"
authors = ["Linas Nikiperavičius <linas@linasdev.com>"]
edition = "2024"
description = "Non-euclidean geometry game engine"
repository = "https://github.com/linasdev/neuclidio"
readme = "README.md"
license = "MIT"
exclude = ["/shaders"]

[dependencies]
delegate = "0.13.5"
log = "0.4.29"
itertools = "0.14.0"
bus = "2.4.1"
crossbeam-channel = "0.5.15"
winit = "0.30.12"
libloading = "0.8.9"
glam = "0.31.0"
vulkanalia-vma = "0.8.0"
obj-rs = "0.7.4"

[dependencies.derive_more]
version = "2.1.1"
features = ["from", "try_into"]

[dependencies.vulkanalia]
version = "0.34.0"
features = ["libloading", "window", "provisional"]

[dev-dependencies]
env_logger = "0.11.8"

[features]
default = []

[[example]]
name = "stanford_dragon"
path = "examples/stanford_dragon/main.rs"
